<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "phi_indexedsearch"
 *
 * Auto generated by Extension Builder 2016-08-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Indexed Search',
	'description' => 'Indexed Search via Cronjob Crawler',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.7',
	'constraints' => array(
		'depends' => array(
			'typo3' => '10.4.1-11.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
	'autoload' => array(
		'classmap' => array('Classes')
	),
);
